name: Bug Report
description: Unexpected behavior or runtime failure
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail so we can reproduce quickly.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Clear and concise description of the bug.
      placeholder: Example: nichebot start exits with code 1 despite valid .env
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Paste exact commands if possible.
      placeholder: |
        1. nichebot doctor
        2. nichebot start
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: node -v
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: Ubuntu 24.04 / macOS 14 / Windows 11
    validations:
      required: true
